// Generated by matugen — do not edit by hand
pragma Singleton
import QtQuick

QtObject {
    readonly property color background: "{{ colors.background.default.hex }}"
    readonly property color surface: "{{ colors.surface.default.hex }}"
    readonly property color surface_container: "{{ colors.surface_container.default.hex }}"
    readonly property color surface_variant: "{{ colors.surface_variant.default.hex }}"
    readonly property color primary: "{{ colors.primary.default.hex }}"
    readonly property color secondary: "{{ colors.secondary.default.hex }}"
    readonly property color on_background: "{{ colors.on_background.default.hex }}"
    readonly property color on_surface: "{{ colors.on_surface.default.hex }}"
    readonly property color on_primary: "{{ colors.on_primary.default.hex }}"
    readonly property color outline: "{{ colors.outline.default.hex }}"
    readonly property color error: "{{ colors.error.default.hex }}"
}
