// Generated by matugen — do not edit by hand
// NOTE: do not use QML property names starting with "on" (reserved for signal handlers)
pragma Singleton
import QtQuick

QtObject {
    readonly property color background: "{{ colors.background.default.hex }}"
    readonly property color surface: "{{ colors.surface.default.hex }}"
    readonly property color surface_container: "{{ colors.surface_container.default.hex }}"
    readonly property color surface_container_high: "{{ colors.surface_container_high.default.hex }}"
    readonly property color surface_variant: "{{ colors.surface_variant.default.hex }}"
    readonly property color primary: "{{ colors.primary.default.hex }}"
    readonly property color secondary: "{{ colors.secondary.default.hex }}"
    readonly property color text: "{{ colors.on_surface.default.hex }}"
    readonly property color text_muted: "{{ colors.on_surface_variant.default.hex }}"
    readonly property color text_on_primary: "{{ colors.on_primary.default.hex }}"
    readonly property color outline: "{{ colors.outline.default.hex }}"
    readonly property color outline_variant: "{{ colors.outline_variant.default.hex }}"
    readonly property color error: "{{ colors.error.default.hex }}"
}
