# Generated by theme-ssot — do not edit by hand
set -gx FZF_DEFAULT_OPTS "--color=fg:#ebe1d4,bg:#202723,hl:#90c6c2,fg+:#1a1008,bg+:#90c6c2,hl+:#1a1008,info:#b1c7c5,prompt:#90c6c2,pointer:#90c6c2,marker:#c2ba9c,spinner:#b1c7c5,header:#8ba7a5"
