# Generated by theme-ssot — do not edit by hand
set -gx FZF_DEFAULT_OPTS "--color=fg:#ebe1d4,bg:#0d1112,hl:#aacade,fg+:#1a1008,bg+:#aacade,hl+:#1a1008,info:#b9cdd7,prompt:#aacade,pointer:#aacade,marker:#c6b1a2,spinner:#b9cdd7,header:#92a7b6"
