# Generated by theme-ssot — do not edit by hand
# Rice wrappers: cava / peaclock / cbonsai / tty-clock / pipes / glow / gum

set -gx GLAMOUR_STYLE "$HOME/.config/glow/ssot.json"
set -gx GUM_CONFIRM_SELECTED_FOREGROUND "ffb688"
set -gx GUM_CONFIRM_PROMPT_FOREGROUND "ebe1d4"
set -gx GUM_FILTER_INDICATOR_FOREGROUND "ffb688"
set -gx GUM_FILTER_MATCH_FOREGROUND "ffb688"
set -gx GUM_FILTER_PROMPT_FOREGROUND "e5bfa9"
set -gx GUM_INPUT_PROMPT_FOREGROUND "ffb688"
set -gx GUM_INPUT_CURSOR_FOREGROUND "ffb688"
set -gx GUM_CHOOSE_SELECTED_FOREGROUND "ffb688"
set -gx GUM_CHOOSE_CURSOR_FOREGROUND "ffb688"
set -gx GUM_SPIN_SPINNER_FOREGROUND "ffb688"

function cava --wraps cava --description 'cava with SSOT theme'
    command cava $argv
end

function peaclock --wraps peaclock --description 'peaclock with SSOT config'
    command peaclock --config-dir "$HOME/.config/peaclock" $argv
end

function cbonsai --wraps cbonsai --description 'cbonsai with SSOT 256-colors'
    if contains -- -k $argv; or contains -- --color $argv
        command cbonsai $argv
    else
        command cbonsai -k 96,187,223,187 $argv
    end
end

function tty-clock --wraps tty-clock --description 'tty-clock with SSOT ANSI color'
    if contains -- -C $argv
        command tty-clock $argv
    else
        command tty-clock -c -b -C 1 $argv
    end
end

function pipes.sh --wraps pipes.sh --description 'pipes.sh with SSOT ANSI colors'
    if contains -- -c $argv
        command pipes.sh $argv
    else
        command pipes.sh -t 1 -c 1 -c 3 -c 6 -c 4 $argv
    end
end

function glow --wraps glow --description 'glow with SSOT glamour style'
    if contains -- -s $argv; or contains -- --style $argv
        command glow $argv
    else
        command glow --style "$HOME/.config/glow/ssot.json" $argv
    end
end

function btm --wraps btm --description 'bottom (btm) — SSOT colors via bottom.toml'
    command btm $argv
end
