# Generated by theme-ssot — do not edit by hand
set -gx FZF_DEFAULT_OPTS "--color=fg:#ebe1d4,bg:#131518,hl:#aabfde,fg+:#1a1008,bg+:#aabfde,hl+:#1a1008,info:#b9c7d7,prompt:#aabfde,pointer:#aabfde,marker:#c6b8a2,spinner:#b9c7d7,header:#92a0b6"
