format = """
[](fg:#6e380f)\
$os\
$username\
[](bg:#ffb688 fg:#6e380f)\
$directory\
[](fg:#ffb688 bg:#e5bfa9)\
$git_branch\
$git_status\
[](fg:#e5bfa9 bg:#cac993)\
$docker_context\
[](fg:#cac993 bg:#3f484a)\
$time\
[ ](fg:#3f484a)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[username]
show_always = true
style_user = "fg:#f7fcfe bg:#6e380f"
style_root = "fg:#ffbbb3 bg:#6e380f"
format = '[$user ]($style)'
disabled = false

[os]
style = "fg:#f7fcfe bg:#6e380f"
disabled = true

[directory]
style = "fg:#512400 bg:#ffb688"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#512400 bg:#e5bfa9"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#512400 bg:#e5bfa9"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#512400 bg:#cac993"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#e5bfa9 bg:#3f484a"
format = '[ ♥ $time ]($style)'
