#!/usr/bin/env bash
# Generated by theme-ssot — do not edit by hand
#
# Chrome roles (SSOT):
#   highlight = primary bg + on_primary fg  (path / session / active window)
#   panel     = surface_container_high + secondary (branch / inactive name)
#   muted     = surface_container + tertiary (time / inactive index)
#
declare -gA THEME_COLORS=(
    [background]="#242423"
    [statusbar-bg]="#343332"
    [statusbar-fg]="#e5bfa9"
    [session-bg]="#ffb688"
    [session-fg]="#1a1008"
    [session-prefix-bg]="#e5bfa9"
    [session-copy-bg]="#cac993"
    [session-search-bg]="#ffb688"
    [session-command-bg]="#6e380f"
    [window-active-base]="#ffb688"
    [window-active-style]="bold"
    [window-inactive-base]="#3f3d3c"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#cac993"
    [pane-border-active]="#ffb688"
    [pane-border-inactive]="#5e5c5a"
    [ok-base]="#3f3d3c"
    [good-base]="#cac993"
    [info-base]="#e5bfa9"
    [warning-base]="#ffb688"
    [error-base]="#ffb4ab"
    [disabled-base]="#5e5c5a"
    [message-bg]="#343332"
    [message-fg]="#e5bfa9"
    [popup-bg]="#343332"
    [popup-fg]="#e5bfa9"
    [popup-border]="#ffb688"
    [menu-bg]="#343332"
    [menu-fg]="#e5bfa9"
    [menu-selected-bg]="#ffb688"
    [menu-selected-fg]="#1a1008"
    [menu-border]="#ffb688"
    # Explicit chrome keys (read by SSOT window-color override below)
    [chrome-highlight-bg]="#ffb688"
    [chrome-highlight-fg]="#1a1008"
    [chrome-panel-bg]="#3f3d3c"
    [chrome-panel-fg]="#e5bfa9"
    [chrome-muted-bg]="#343332"
    [chrome-muted-fg]="#cac993"
)

# Pin PowerKit index strips to SSOT muted/highlight (not auto +20% -lighter).
_ssot_pin_powerkit_chrome() {
    [[ -n "${THEME_COLORS[chrome-highlight-bg]:-}" ]] &&
        _COLOR_VARIANTS["window-active-base-lighter"]="${THEME_COLORS[chrome-highlight-bg]}"
    [[ -n "${THEME_COLORS[chrome-muted-bg]:-}" ]] &&
        _COLOR_VARIANTS["window-inactive-base-lighter"]="${THEME_COLORS[chrome-muted-bg]}"
}

# Split index vs name colors (PowerKit normally forces the same fg for both).
# Active:  index+name on highlight (peach) with dark text
# Inactive: index = muted fg on muted bg; name = panel fg on panel bg
_ssot_windows_get_colors() {
    local state="$1"
    local index_bg index_fg content_bg content_fg style

    if [[ "$state" == "active" ]]; then
        index_bg=$(resolve_color "chrome-highlight-bg")
        index_fg=$(resolve_color "chrome-highlight-fg")
        content_bg=$(resolve_color "window-active-base")
        content_fg=$(resolve_color "chrome-highlight-fg")
    else
        index_bg=$(resolve_color "chrome-muted-bg")
        index_fg=$(resolve_color "chrome-muted-fg")
        content_bg=$(resolve_color "window-inactive-base")
        content_fg=$(resolve_color "chrome-panel-fg")
    fi
    style=$(get_window_style "$state")
    printf '%s %s %s %s %s' "$index_bg" "$index_fg" "$content_bg" "$content_fg" "$style"
}

if declare -F _windows_get_colors >/dev/null 2>&1; then
    _windows_get_colors() { _ssot_windows_get_colors "$@"; }
fi

if declare -F generate_color_variants >/dev/null 2>&1 && [[ -z "${_SSOT_GENERATE_WRAPPED:-}" ]]; then
    _SSOT_GENERATE_WRAPPED=1
    eval "_ssot_orig_generate_color_variants() $(declare -f generate_color_variants | tail -n +2)"
    generate_color_variants() {
        _ssot_orig_generate_color_variants "$@"
        _ssot_pin_powerkit_chrome
    }
fi

# When theme colors load from cache, re-pin strips + reinstall window override.
if declare -F deserialize_theme_colors >/dev/null 2>&1 && [[ -z "${_SSOT_DESER_WRAPPED:-}" ]]; then
    _SSOT_DESER_WRAPPED=1
    eval "_ssot_orig_deserialize_theme_colors() $(declare -f deserialize_theme_colors | tail -n +2)"
    deserialize_theme_colors() {
        _ssot_orig_deserialize_theme_colors "$@"
        _ssot_pin_powerkit_chrome
        if declare -F _windows_get_colors >/dev/null 2>&1; then
            _windows_get_colors() { _ssot_windows_get_colors "$@"; }
        fi
    }
fi

_ssot_pin_powerkit_chrome
