-- Generated by theme-ssot — do not edit by hand
-- Loaded by lua/plugins/ssot-colors.lua
return {
  meta = {
    harmony = "sand",
    family = "sand",
  },
  background = "#181316",
  surface = "#1d181c",
  surface_container = "#292126",
  surface_variant = "#574451",
  primary = "#ffb688",
  secondary = "#e5bfa9",
  tertiary = "#cac993",
  on_primary = "#1a1008",
  on_surface = "#ebe1d4",
  on_surface_variant = "#d1c5b4",
  outline = "#c4a882",
  error = "#ffb4ab",
  primary_container = "#6e380f",
}
