-- Generated by theme-ssot — do not edit by hand
-- Loaded by lua/plugins/ssot-colors.lua
return {
  meta = {
    harmony = "mist-blue",
    family = "cool",
  },
  background = "#131518",
  surface = "#171a1e",
  surface_container = "#1f242a",
  surface_variant = "#414b5a",
  primary = "#aabfde",
  secondary = "#b9c7d7",
  tertiary = "#c6b8a2",
  on_primary = "#1a1008",
  on_surface = "#ebe1d4",
  on_surface_variant = "#d1c5b4",
  outline = "#92a0b6",
  error = "#ffb4ab",
  primary_container = "#324766",
}
