#!/usr/bin/env bash
# Compile the ds shaders to .qsb. Qt cannot load raw GLSL at runtime, so the
# .qsb files are committed; re-run this after editing any .frag / .vert.
#
# A ShaderEffect shares ONE uniform block between its stages, and qsb rejects a
# mismatch. For liquidglass the vertex shader is therefore generated from the
# fragment shader's block rather than hand-maintained — editing one file only.
set -euo pipefail

cd "$(dirname "$0")"

QSB="${QSB:-}"
if [[ -z "${QSB}" ]]; then
  for c in qsb /usr/lib/qt6/bin/qsb /usr/lib/qt6/qsb; do
    if command -v "${c}" >/dev/null 2>&1 || [[ -x "${c}" ]]; then QSB="${c}"; break; fi
  done
fi
if [[ -z "${QSB}" ]]; then
  echo "qsb not found (pacman -S qt6-shadertools)" >&2
  exit 1
fi

TARGETS='100 es,120,150'

gen_vert_from_frag() {
  python3 - "$1" "$2" <<'PY'
import pathlib, re, sys
frag, vert = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
block = re.search(r"layout\(std140, binding = 0\) uniform buf \{.*?\};",
                  frag.read_text(), re.S)
if not block:
    raise SystemExit(f"{frag}: no std140 uniform block found")
vert.write_text(f"""#version 440

// Generated by build-shaders.sh from {frag.name} — do not edit by hand.
// A pass-through vertex stage that mirrors the fragment uniform block, because
// ShaderEffect binds one block across both stages.

layout(location = 0) in vec4 qt_Vertex;
layout(location = 1) in vec2 qt_MultiTexCoord0;
layout(location = 0) out vec2 qt_TexCoord0;

{block.group(0)}

void main() {{
    qt_TexCoord0 = qt_MultiTexCoord0;
    gl_Position = qt_Matrix * qt_Vertex;
}}
""")
PY
}

gen_vert_from_frag liquidglass.frag liquidglass.vert

for src in liquidglass.frag liquidglass.vert glassedge.frag glassedge.vert; do
  [[ -f "${src}" ]] || continue
  "${QSB}" --glsl "${TARGETS}" --hlsl 50 --msl 12 -o "${src}.qsb" "${src}"
  echo "built ${src}.qsb"
done

# Quickshell hot-reload watches .qml, not .qsb, and Qt caches a compiled shader
# by URL — so a rebuilt .qsb does NOT take effect in a running shell. Restart it,
# or you will spend the evening judging art direction against a stale shader.
echo "NOTE: restart the shell to pick these up:  pkill -x quickshell && quickshell -c rice -n -d"
