#version 440

// Generated by build-shaders.sh from liquidglass.frag — do not edit by hand.
// A pass-through vertex stage that mirrors the fragment uniform block, because
// ShaderEffect binds one block across both stages.

layout(location = 0) in vec4 qt_Vertex;
layout(location = 1) in vec2 qt_MultiTexCoord0;
layout(location = 0) out vec2 qt_TexCoord0;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    float itemW;      // padded item size, px
    float itemH;
    float srcX;       // padded item origin, in source-texture uv
    float srcY;
    float srcW;       // padded item span, in source-texture uv
    float srcH;
    float pad;        // shadow ring, px
    float radius;
    float corner;     // 2 = circular arc, ~4 = squircle (continuous curvature)
    float bevel;      // refracting round-over width, px
    float lens;       // max sample displacement, px
    float disperse;   // chromatic spread, as a fraction of lens
    float absorb;     // fraction of the backdrop that passes through the glass
    float veil;       // the sheet's own scatter; glass has body, blacks are never 0
    float satur;
    float lipWidth;   // catch-light falloff, px — must survive at 100% zoom
    float bodyTilt;   // light gathers at the top of the sheet, falls off below
    float specA;      // white catch-light on the lip
    float lipDarkA;   // dark hairline on the lip (light glass needs this)
    float causticA;   // bright line where the round-over meets the flat
    float innerA;     // thickness shading
    float shadowA;
    float shadowSize;
    float blurTexelX;  // one texel of the downsampled frost texture
    float blurTexelY;
};

void main() {
    qt_TexCoord0 = qt_MultiTexCoord0;
    gl_Position = qt_Matrix * qt_Vertex;
}
