-- Generated by theme-ssot — do not edit by hand
-- Loaded via require("colors-matugen") from hyprland.lua

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(aabfdeee)", "rgba(b9c7d7ee)" }, angle = 45 },
            inactive_border = "rgba(414b5aaa)",
        },
    },
})
