-- Generated by theme-ssot — do not edit by hand
-- Loaded via require("colors-matugen") from hyprland.lua

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(90c4c6ee)", "rgba(b1c7c7ee)" }, angle = 45 },
            inactive_border = "rgba(3b4f54aa)",
        },
    },
})
