-- Generated by theme-ssot — do not edit by hand
-- Loaded via require("colors-matugen") from hyprland.lua

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(ffb688ee)", "rgba(e5bfa9ee)" }, angle = 45 },
            inactive_border = "rgba(574451aa)",
        },
    },
})
