-- Generated by nwg-displays — converted to Lua

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@165.0",
    position = "0x0",
    scale = 1,
    transform = 1,
})

hl.monitor({
    output = "DP-3",
    mode = "2560x1440@164.8",
    position = "1080x480",
    scale = 1,
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})
