// Generated by theme-ssot — do not edit by hand
// NOTE: do not use QML property names starting with "on" (reserved for signal handlers)
pragma Singleton
import QtQuick

QtObject {
    readonly property color background: "#0d1112"
    readonly property color surface: "#111617"
    readonly property color surface_container: "#1a2224"
    readonly property color surface_container_high: "#222d30"
    readonly property color surface_variant: "#3b4f54"
    readonly property color primary: "#90c4c6"
    readonly property color secondary: "#b1c7c7"
    readonly property color text: "#ebe1d4"
    readonly property color text_muted: "#d1c5b4"
    readonly property color text_on_primary: "#1a1008"
    readonly property color outline: "#8ba6a7"
    readonly property color outline_variant: "#3b4f54"
    readonly property color error: "#ffb4ab"
    // Chrome tokens — bars/widgets (tmux / starship / QS islands)
    readonly property color chrome_highlight_bg: "#90c4c6"
    readonly property color chrome_highlight_fg: "#1a1008"
    readonly property color chrome_panel_bg: "#222d30"
    readonly property color chrome_panel_fg: "#b1c7c7"
    readonly property color chrome_muted_bg: "#1a2224"
    readonly property color chrome_muted_fg: "#c2be9c"
    readonly property string font_mono: "JetBrains Mono"
    readonly property string font_ui: "Adwaita Sans"
}
