// Generated by matugen — do not edit by hand
pragma Singleton
import QtQuick

QtObject {
    readonly property color background: "#19120d"
    readonly property color surface: "#19120d"
    readonly property color surface_container: "#261e19"
    readonly property color surface_variant: "#52443c"
    readonly property color primary: "#ffb688"
    readonly property color secondary: "#e5bfa9"
    readonly property color on_background: "#f0dfd7"
    readonly property color on_surface: "#f0dfd7"
    readonly property color on_primary: "#512400"
    readonly property color outline: "#9f8d83"
    readonly property color error: "#ffb4ab"
}
